# Configuration file for llama2-7b sketcher
n_gpu_layers: -1  # Use all available GPU layers
n_ctx: 5120       # Context window size
max_tokens: 500  # Maximum tokens to generate
n_threads: 1      # Number of CPU threads
timeout_seconds: 60  # Timeout for generation operations
n_batch: 512
verbose: false
logits_all: true

# Generation parameters
temperature: 0.8
# top_p: 0.9
top_p: 1.0
top_k: 40
min_p: 0.1
# tfs_z: 1.0
frequency_penalty: 1.2