# Configuration file for llama2-7b sketcher
n_gpu_layers: -1  # Use all available GPU layers
<<<<<<< HEAD:configs/llama_cpp.yml
n_ctx: 5120       # Context window size
n_threads: 1      # Number of CPU threads
timeout_seconds: 60  # Timeout for generation operations
n_batch: 512
verbose: false
logits_all: true
=======
n_batch: 512
n_threads: 1      # Number of CPU threads
n_ctx: 4096       # Context window size
verbose: false
>>>>>>> 2bc58cbef31857f1b697f56f2da4554c232982ca:configs/llamacpp.yml
