# Configuration file for llama2-7b sketcher
n_gpu_layers: -1  # Use all available GPU layers
n_ctx: 5120       # Context window size
n_threads: 1      # Number of CPU threads
timeout_seconds: 60  # Timeout for generation operations
n_batch: 512
verbose: false
logits_all: true